// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel ProcessTrailMap

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> TrailMap;
float evaporateSpeed;
uint width;
uint height;
float deltaTime;

[numthreads(8,8,1)]
void ProcessTrailMap (uint3 id : SV_DispatchThreadID)
{
    if (id.x < 0 || id.x >= width || id.y < 0 || id.y >= height) {
        return;
    }

    float4 originalValue = TrailMap[id.xy];
    float4 evaporateValue = max(0, originalValue - evaporateSpeed * deltaTime);

    TrailMap[id.xy] = evaporateValue;
}
